name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '16'
          - '18'
          - '20'
          - '22'

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: install & start PostgreSQL with PostGIS
      # pin to commit that changes it to use the postgis/postgis Docker image, which we need for PostgreSQL version 14
      uses: huaxk/postgis-action@0e3a7a41c0b06b9a1fe690d937f21168af8839bd
      with:
        postgresql password: password
        postgresql user: postgres
        postgresql db: postgres
        postgresql version: '14-3.4-alpine'

    - name: install & start Redis
      uses: supercharge/redis-github-action@1.8.0
      # with:
      #   redis-version: ${{ matrix.redis-version }}

    - run: npm install

    - run: npm run lint
    - run: npm test
      env:
        PGHOST: localhost
        PGPORT: '5432'
        PGUSER: postgres
        PGPASSWORD: password
        PGDATABASE: postgres
        DEBUG: 'match-gtfs-rt-to-gtfs:*'
